### ISSUE TITLE
defineModel使えるところで使う

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/Jomon-UI#144]
参考
https://ja.vuejs.org/guide/components/v-model
https://qiita.com/whopper1962/items/2335618146ec52aa4c81
https://github.com/traPtitech/traPortfolio-Dashboard/pull/237

components/shared内とかに結構ありそう
いくつかに絞ってでも改善できると助かる

**Comment by ogu-kazemiya** [comment]
QSoCで自分がやる予定です
