### ISSUE TITLE
申請の払い戻し対象を一人に制限する

### ISSUE THREAD

**Issue by reiroop** [traPtitech/Jomon-UI#170]
発端↓
https://q.trap.jp/messages/21b46b2d-d77f-4c23-a0a9-1a014e1ac90a

**Comment by mehm8128** [comment]
これってhttps://github.com/traPtitech/Jomon-UI/issues/171 をやるなら申請作成時は自動で申請作成者を払い戻し対象者に入れるようにすれば何か追加で実装する必要はなかったりしませんか？

**Comment by reiroop** [comment]
忘れてました、そうですね
